const PROGRESSIVE_BLUR_DEFAULT_HEIGHT = '30%'

const PROGRESSIVE_BLUR_DEFAULT_POSITION = 'bottom' as const

const PROGRESSIVE_BLUR_DEFAULT_LEVELS = [
  0.5, 1, 2, 4, 8, 16, 32, 64
] as const

const PROGRESSIVE_BLUR_LAYER_STEP_PERCENTAGE = 12.5

const PROGRESSIVE_BLUR_FULL_MASK =
  'linear-gradient(rgba(0,0,0,0) 0%, rgba(0,0,0,1) 5%, rgba(0,0,0,1) 95%, rgba(0,0,0,0) 100%)'

export {
  PROGRESSIVE_BLUR_DEFAULT_HEIGHT,
  PROGRESSIVE_BLUR_DEFAULT_LEVELS,
  PROGRESSIVE_BLUR_DEFAULT_POSITION,
  PROGRESSIVE_BLUR_FULL_MASK,
  PROGRESSIVE_BLUR_LAYER_STEP_PERCENTAGE
}
