const INITIAL_ANIMATED_BEAM_LINEAR_GRADIENT_POSITION = {
  x1: '0%',
  x2: '0%',
  y1: '0%',
  y2: '0%'
} as const

const ANIMATED_BEAM_GRADIENT_START_COLOR = 'var(--color-primary)'
const ANIMATED_BEAM_GRADIENT_STOP_COLOR = 'var(--color-secondary)'

export {
  ANIMATED_BEAM_GRADIENT_START_COLOR,
  ANIMATED_BEAM_GRADIENT_STOP_COLOR,
  INITIAL_ANIMATED_BEAM_LINEAR_GRADIENT_POSITION
}
