const WARP_DIALOG_CONTENT_ANIMATION_DURATION = 0.35
const WARP_DIALOG_ENTER_DURATION = 0.5
const WARP_DIALOG_EXIT_DURATION = 0.25
const WARP_DIALOG_ANIMATION_EASE = [0.59, 0, 0.35, 1] as const
const WARP_DIALOG_ANIMATION_REPEAT_DELAY = 0.35
const WARP_DIALOG_ANIMATION_REPEAT_DURATION = 15
const WARP_DIALOG_INITIAL_BACKGROUND_COLOR = 'var(--secondary)'
const WARP_DIALOG_ACTIVE_BACKGROUND_COLOR = 'var(--primary)'
const WARP_DIALOG_LOOPING_ANIMATION = {
  opacity: 0.9,
  scale: [1, 0.7, 1],
  transition: {
    duration: WARP_DIALOG_ENTER_DURATION,
    scale: {
      delay: WARP_DIALOG_ANIMATION_REPEAT_DELAY,
      duration: WARP_DIALOG_ANIMATION_REPEAT_DURATION,
      ease: 'easeInOut',
      repeat: Infinity,
      repeatType: 'loop'
    }
  }
}

export {
  WARP_DIALOG_ACTIVE_BACKGROUND_COLOR,
  WARP_DIALOG_ANIMATION_EASE,
  WARP_DIALOG_LOOPING_ANIMATION,
  WARP_DIALOG_ANIMATION_REPEAT_DELAY,
  WARP_DIALOG_ANIMATION_REPEAT_DURATION,
  WARP_DIALOG_CONTENT_ANIMATION_DURATION,
  WARP_DIALOG_ENTER_DURATION,
  WARP_DIALOG_EXIT_DURATION,
  WARP_DIALOG_INITIAL_BACKGROUND_COLOR
}
