const DEFAULT_MORPH_SQUARE_BORDER_RADIUS = ['25%', '50%', '25%']
const DEFAULT_MORPH_SQUARE_ROTATE_ANIMATION = [0, 180, 360]

export {
  DEFAULT_MORPH_SQUARE_BORDER_RADIUS,
  DEFAULT_MORPH_SQUARE_ROTATE_ANIMATION
}
