const GRADIENT_BACKGROUND_DEFAULT_COLORS = [
  '#0A0A0A',
  '#2979FF',
  '#FF80AB',
  '#FF6D00',
  '#FFD600',
  '#00E676',
  '#3D5AFE'
]

const GRADIENT_BACKGROUND_DEFAULT_STOPS = [
  35, 50, 60, 70, 80, 90, 100
]

const GRADIENT_BACKGROUND_DEFAULT_CONTAINER_STYLE = {}

export {
  GRADIENT_BACKGROUND_DEFAULT_COLORS,
  GRADIENT_BACKGROUND_DEFAULT_CONTAINER_STYLE,
  GRADIENT_BACKGROUND_DEFAULT_STOPS
}
