const SIDEBAR_STORAGE_KEY = 'sidebar_state'

const SIDEBAR_WIDTH = '20rem'

const SIDEBAR_WIDTH_MOBILE = '18rem'

const SIDEBAR_WIDTH_ICON = '3.6rem'

const SIDEBAR_KEYBOARD_SHORTCUT = 'b'

export {
  SIDEBAR_KEYBOARD_SHORTCUT,
  SIDEBAR_STORAGE_KEY,
  SIDEBAR_WIDTH,
  SIDEBAR_WIDTH_ICON,
  SIDEBAR_WIDTH_MOBILE
}
