const ORBITING_CIRCLES_DURATION = 20
const ORBITING_CIRCLES_RADIUS = 160
const ORBITING_CIRCLES_PATH = true
const ORBITING_CIRCLES_ICON_SIZE = 30
const ORBITING_CIRCLES_SPEED = 1

export {
  ORBITING_CIRCLES_DURATION,
  ORBITING_CIRCLES_ICON_SIZE,
  ORBITING_CIRCLES_PATH,
  ORBITING_CIRCLES_RADIUS,
  ORBITING_CIRCLES_SPEED
}
