import { Check, Copy } from 'lucide-react'

const CLIPBOARD_DEFAULT_ICON = <Copy />
const CLIPBOARD_FEEDBACK_ICON = <Check />

const CLIPBOARD_DEFAULT_ICON_PROPS = {
  default: CLIPBOARD_DEFAULT_ICON,
  feedback: CLIPBOARD_FEEDBACK_ICON
} as const

const CLIPBOARD_FEEDBACK_RESET_DELAY = 1500

export {
  CLIPBOARD_DEFAULT_ICON,
  CLIPBOARD_DEFAULT_ICON_PROPS,
  CLIPBOARD_FEEDBACK_ICON,
  CLIPBOARD_FEEDBACK_RESET_DELAY
}
